# Aufruf:   docker compose up postgres pgadmin fakesmtp film
#           docker compose down

# Netzwerk "film_default" für die Container durch den Verzeichnisnamen
---
# https://docs.docker.com/compose/compose-file
# https://docs.docker.com/compose/compose-file/compose-file-v3
services:

  # ------------------------------------------------------------------------------------
  # P o s t g r e S Q L
  # ------------------------------------------------------------------------------------
  postgres:
    image: postgres:15.2-bullseye
    ports:
      - published: 5432
        target: 5432
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/postgres/data
        target: /var/lib/postgresql/data
      - type: bind
        source: C:/Zimmermann/volumes/postgres/postgresql.conf
        target: /etc/postgresql/postgresql.conf
        read_only: true
      - type: bind
        source: C:/Zimmermann/volumes/postgres/tablespace
        target: /var/lib/postgresql/tablespace
      - type: bind
        source: C:/Zimmermann/volumes/postgres/csv/film
        target: /csv
        read_only: true
      - type: bind
        source: C:/Zimmermann/volumes/postgres/sql
        target: /sql
        read_only: true
      - type: bind
        source: .extras/db/postgres/SQL
        target: /sql
    environment:
      POSTGRES_PASSWORD: p
      TZ: Europe/Berlin
      PGTZ: Europe/Berlin
      #PGDATA: /var/lib/postgresql/data
      # https://www.postgresql.org/docs/current/auth-trust.html
      #POSTGRES_HOST_AUTH_METHOD: trust
    user: "postgres:postgres"
    security_opt:
      - label:user:postgres
      - no-new-privileges:true
    container_name: postgres
    hostname: postgres
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
    healthcheck:
      test:
        [
          CMD,
          pg_isready,
          --dbname,
          postgres,
          --username,
          postgres
        ]
      interval: 5s
      timeout: 2s
      start_period: 5s

  # ------------------------------------------------------------------------------------
  # p g a d m i n
  # ------------------------------------------------------------------------------------
  # http://localhost:8888 mit Emailadresse "pgadmin@acme.com" und Passwort "p"
  pgadmin:
    image: dpage/pgadmin4:7.1
    ports:
      - published: 8888
        target: 80
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/postgres/pgadmin
        # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
        target: /var/lib/pgadmin
      - type: bind
        source: C:/Zimmermann/volumes/postgres/pgadmin4
        target: /var/lib/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@acme.com
      PGADMIN_DEFAULT_PASSWORD: p
    user: "pgadmin:5050"
    container_name: pgadmin
    hostname: pgadmin
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
          
  # ------------------------------------------------------------------------------------
  # f a k e s m t p
  # ------------------------------------------------------------------------------------
  fakesmtp:
    image: gessnerfl/fake-smtp-server:1.10.4
    ports:
      - published: 5025
        target: 5025
      - published: 5080
        target: 5080
      - published: 5081
        target: 5081
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/fakesmtp
        target: /tmp
    environment:
      TZ: Europe/Berlin
      SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
      SPRING_MAIN_BANNER-MODE: LOG
      SPRING_LAZY-INITIALIZATION: "true"
      SPRING_JPA_OPEN-IN-VIEW: "true"
    container_name: fakesmtp
    hostname: fakesmtp
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 768M

  # ------------------------------------------------------------------------------------
  # f i l m
  # ------------------------------------------------------------------------------------
  film:
    image: juergenzimmermann/film:2023.1.0
    ports:
      - published: 3000
        target: 3000
    volumes:
      - type: bind
        source: C:\Zimmermann\volumes\film
        target: /opt/app/log
    env_file: [ "docker-compose.env" ]
    environment:
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution
      USER_PASSWORD_ENCODED: "$$argon2i$$v=19$$m=4096,t=3,p=1$$aaxA2v/9rRSPGkwYN+NQog$$27Huii1XtD3iEd62fog+04G26LRPZMHoYCI6AGKTL8M"
    container_name: film
    hostname: film
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M