name: Film Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14.x"

    - name: Install dependencies
      run: npm install
    
    - name: Update Ubuntu
      run: |
        sudo apt-get update --yes
        sudo apt-get upgrade --yes

    - name: run tests
      run: npm run test

    - name: eslint
      run: npm run eslint

    - name: Security audit
      run: npm run audit --omit=dev

    - name: AsciiDoctor
      run: npm run asciidoctor

    - name: reveal.js
      run: npm run revealjs

    - name: Typedoc
      run: npm run typedoc
      